package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/nirnx/zester/pkg/auth"
)

// The `zester auth init` verb generates the NATS operator/account/user JWT
// hierarchy and a matching nats-server.conf — the trust plane that the
// external NATS server and the zester daemons authenticate against. Together
// with `zester ca` (the TLS plane) it makes a bare-metal bootstrap fully
// CLI-driven: no hand-written nsc scripts, no separate bootstrap tool.
//
// Like `zester ca`, this is OFFLINE: pure local file I/O, no NATS connection.

var authDir string

var authCmd = &cobra.Command{
	Use:   "auth",
	Short: "Manage the NATS auth hierarchy (operator/account/user JWTs) — offline",
	Long: `Manage Zester's NATS authentication material.

'zester auth init' generates the operator + account + system-account JWT
hierarchy, the master and admin user credentials, and a nats-server.conf that
trusts them (MEMORY resolver, JetStream enabled). Run once on the first master
host during provisioning, alongside 'zester ca init'.`,
}

var authInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate the operator/account/user JWT hierarchy + nats-server.conf",
	RunE: func(cmd *cobra.Command, args []string) error {
		natsConf, _ := cmd.Flags().GetString("nats-conf")
		storeDir, _ := cmd.Flags().GetString("jetstream-store")
		certFile, _ := cmd.Flags().GetString("nats-cert")
		keyFile, _ := cmd.Flags().GetString("nats-key")
		force, _ := cmd.Flags().GetBool("force")

		// Refuse to clobber an existing hierarchy unless --force: account.seed
		// is the fleet trust root (it signs every peel JWT) — regenerating it
		// invalidates every issued credential.
		seedPath := filepath.Join(authDir, "account.seed")
		if _, err := os.Stat(seedPath); err == nil && !force {
			return fmt.Errorf("auth material already exists in %s (account.seed present); pass --force to regenerate (invalidates all issued credentials)", authDir)
		}
		if err := os.MkdirAll(authDir, 0700); err != nil {
			return fmt.Errorf("create auth dir: %w", err)
		}

		operatorKP, err := auth.GenerateKeyBundle(auth.RoleOperator)
		if err != nil {
			return fmt.Errorf("generate operator key: %w", err)
		}
		accountKP, err := auth.GenerateKeyBundle(auth.RoleAccount)
		if err != nil {
			return fmt.Errorf("generate account key: %w", err)
		}
		sysAccountKP, err := auth.GenerateKeyBundle(auth.RoleAccount)
		if err != nil {
			return fmt.Errorf("generate system-account key: %w", err)
		}

		operatorJWT, err := auth.CreateOperatorJWT(operatorKP, auth.OperatorJWTOptions{
			Name:          "zester-op",
			SystemAccount: sysAccountKP.PublicKey,
		})
		if err != nil {
			return fmt.Errorf("create operator JWT: %w", err)
		}
		accountJWT, err := auth.CreateAccountJWT(accountKP, operatorKP, auth.AccountJWTOptions{
			Name:      "zester-acct",
			JetStream: true,
		})
		if err != nil {
			return fmt.Errorf("create account JWT: %w", err)
		}
		sysAccountJWT, err := auth.CreateAccountJWT(sysAccountKP, operatorKP, auth.AccountJWTOptions{Name: "SYS"})
		if err != nil {
			return fmt.Errorf("create system-account JWT: %w", err)
		}

		// Operator/account JWTs + the account seed (master reloads it).
		writes := []struct {
			name string
			data []byte
			mode os.FileMode
		}{
			{"operator.jwt", []byte(operatorJWT), 0644},
			{"account.jwt", []byte(accountJWT), 0644},
		}
		for _, w := range writes {
			if err := os.WriteFile(filepath.Join(authDir, w.name), w.data, w.mode); err != nil {
				return fmt.Errorf("write %s: %w", w.name, err)
			}
		}
		if err := accountKP.SaveSeedToFile(seedPath); err != nil {
			return fmt.Errorf("save account seed: %w", err)
		}

		// master.creds (daemon) and admin.creds (CLI/operator).
		for _, u := range []struct {
			name string
			opts auth.UserJWTOptions
		}{
			{"master.creds", auth.MasterUserJWTOptions(accountKP.PublicKey)},
			{"admin.creds", auth.AdminUserJWTOptions(accountKP.PublicKey)},
		} {
			userKP, err := auth.GenerateKeyBundle(auth.RoleUser)
			if err != nil {
				return fmt.Errorf("generate %s key: %w", u.name, err)
			}
			jwt, err := auth.CreateUserJWT(userKP, accountKP, u.opts)
			if err != nil {
				return fmt.Errorf("create %s JWT: %w", u.name, err)
			}
			if err := auth.WriteCredsFile(filepath.Join(authDir, u.name), jwt, userKP.Seed); err != nil {
				return fmt.Errorf("write %s: %w", u.name, err)
			}
		}

		// nats-server.conf: operator mode, MEMORY resolver preloading the
		// account + system account, JetStream enabled, TLS pointing at the
		// (separately, via 'zester ca') issued NATS server cert.
		conf := fmt.Sprintf(`# Generated by 'zester auth init'. Point nats-server at this file.
port: 4222
tls {
  cert_file: %s
  key_file: %s
}
jetstream {
  store_dir: %s
}
operator: %s
system_account: %s
resolver: MEMORY
resolver_preload: {
  %s: %s
  %s: %s
}
`, certFile, keyFile, storeDir,
			filepath.Join(authDir, "operator.jwt"), sysAccountKP.PublicKey,
			accountKP.PublicKey, accountJWT, sysAccountKP.PublicKey, sysAccountJWT)
		if err := os.WriteFile(natsConf, []byte(conf), 0644); err != nil {
			return fmt.Errorf("write nats-server.conf: %w", err)
		}

		fmt.Printf("NATS auth hierarchy initialized in %s\n\n", authDir)
		fmt.Printf("  operator.jwt / account.jwt / account.seed\n")
		fmt.Printf("  master.creds  (zester-master)\n")
		fmt.Printf("  admin.creds   (operator CLI)\n")
		fmt.Printf("  nats-server.conf → %s\n\n", natsConf)
		fmt.Println("Next steps:")
		fmt.Println("  1. zester ca init && zester ca issue nats-server --dns <name> --out <tls-dir>")
		fmt.Println("     (the nats-server.conf tls{} block above must point at that cert/key).")
		fmt.Printf("  2. Start nats-server with -c %s\n", natsConf)
		fmt.Println("  3. Multi-master: replicate this auth dir (esp. account.seed) to every master.")
		return nil
	},
}

func init() {
	authCmd.PersistentFlags().StringVar(&authDir, "dir", "/var/lib/zester/auth", "auth directory")
	authInitCmd.Flags().String("nats-conf", "/etc/nats/nats-server.conf", "path to write the generated nats-server.conf")
	authInitCmd.Flags().String("jetstream-store", "/var/lib/nats/jetstream", "JetStream store_dir in the generated config")
	authInitCmd.Flags().String("nats-cert", "/var/lib/zester/auth/nats-server.crt", "NATS server certificate path referenced by the generated config")
	authInitCmd.Flags().String("nats-key", "/var/lib/zester/auth/nats-server.key", "NATS server key path referenced by the generated config")
	authInitCmd.Flags().Bool("force", false, "regenerate even if auth material exists (invalidates all issued credentials)")

	authCmd.AddCommand(authInitCmd)
	authCmd.AddCommand(authLintCmd)
	rootCmd.AddCommand(authCmd)
}
