// Package moduledoc is the CLI-side, offline documentation source for
// self-documenting modules (keystone spec §7): it embeds docdata.json —
// generated by cmd/zester-docgen from the live module registries, gated on
// spec presence — and serves it back as modschema.ModuleInfo through Lookup
// and All. The planned Phase-4 `zester doc` command will render these through
// the same modschema.RenderText a connected daemon uses for a live
// Spec.Info(), so operator-facing docs will work identically whether or not a
// master is reachable. That offline CLI surface is not built yet; this package
// is the embedded data source it will read.
//
// moduledoc is a leaf: it imports only modschema (never pkg/state, pkg/
// execmod, or internal/*), so it will never pull execution-layer code into the
// zester CLI binary just to answer the future `zester doc`.
package moduledoc

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	"github.com/nirnx/zester/pkg/modschema"
)

//go:embed docdata.json
var docdataJSON []byte

var (
	loadOnce sync.Once
	byModule map[string]modschema.ModuleInfo
	loadErr  error
)

// load lazily decodes the embedded docdata.json exactly once. A malformed
// embedded file is a build-time packaging defect, not a runtime condition a
// caller can recover from productively — Lookup/All surface it as loadErr
// rather than panicking, so a caller (or a test) can still report it cleanly.
func load() {
	loadOnce.Do(func() {
		var all []modschema.ModuleInfo
		if err := json.Unmarshal(docdataJSON, &all); err != nil {
			loadErr = fmt.Errorf("moduledoc: embedded docdata.json is invalid: %w", err)
			return
		}
		byModule = make(map[string]modschema.ModuleInfo, len(all))
		for _, mi := range all {
			byModule[mi.Module] = mi
		}
	})
}

// Lookup returns the embedded ModuleInfo for module, or (zero, false) if it
// has no entry (not yet migrated to a self-documenting schema, or an unknown
// name).
func Lookup(module string) (modschema.ModuleInfo, bool) {
	load()
	if loadErr != nil {
		return modschema.ModuleInfo{}, false
	}
	mi, ok := byModule[module]
	if !ok {
		return modschema.ModuleInfo{}, false
	}
	// Cloned on egress: byModule is a process-wide cache and every returned
	// documentation view must be safe to vandalize (round 5).
	return mi.Clone(), true
}

// All returns every embedded ModuleInfo, sorted by Module name.
func All() []modschema.ModuleInfo {
	load()
	out := make([]modschema.ModuleInfo, 0, len(byModule))
	for _, mi := range byModule {
		out = append(out, mi.Clone())
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Module < out[j].Module })
	return out
}

// LoadError returns the error from decoding the embedded docdata.json, or nil
// if it decoded successfully (or hasn't been consulted yet — Lookup/All
// trigger the load). Exposed so a startup or CI check can fail loudly on a
// corrupt embed instead of silently reporting every module as undocumented.
func LoadError() error {
	load()
	return loadErr
}
